name: pr
on: [pull_request]

jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Run linter"
        uses: stefanoeb/eslint-action@1.0.2

      - name: "Run tests"
        run: npm run test:unit